// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extract.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExtractRequest struct {
	Transaction          string   `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractRequest) Reset()         { *m = ExtractRequest{} }
func (m *ExtractRequest) String() string { return proto.CompactTextString(m) }
func (*ExtractRequest) ProtoMessage()    {}
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6facc52bf885d4, []int{0}
}

func (m *ExtractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractRequest.Unmarshal(m, b)
}
func (m *ExtractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractRequest.Marshal(b, m, deterministic)
}
func (m *ExtractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractRequest.Merge(m, src)
}
func (m *ExtractRequest) XXX_Size() int {
	return xxx_messageInfo_ExtractRequest.Size(m)
}
func (m *ExtractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractRequest proto.InternalMessageInfo

func (m *ExtractRequest) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func (m *ExtractRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *ExtractRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type ExtractResponse struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractResponse) Reset()         { *m = ExtractResponse{} }
func (m *ExtractResponse) String() string { return proto.CompactTextString(m) }
func (*ExtractResponse) ProtoMessage()    {}
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca6facc52bf885d4, []int{1}
}

func (m *ExtractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractResponse.Unmarshal(m, b)
}
func (m *ExtractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractResponse.Marshal(b, m, deterministic)
}
func (m *ExtractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractResponse.Merge(m, src)
}
func (m *ExtractResponse) XXX_Size() int {
	return xxx_messageInfo_ExtractResponse.Size(m)
}
func (m *ExtractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractResponse proto.InternalMessageInfo

func (m *ExtractResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func init() {
	proto.RegisterType((*ExtractRequest)(nil), "api.ExtractRequest")
	proto.RegisterType((*ExtractResponse)(nil), "api.ExtractResponse")
}

func init() { proto.RegisterFile("extract.proto", fileDescriptor_ca6facc52bf885d4) }

var fileDescriptor_ca6facc52bf885d4 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x28, 0x29,
	0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0x92,
	0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f,
	0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x51, 0x4a, 0xe3, 0xe2, 0x73, 0x85, 0xe8, 0x09,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe0, 0xe2, 0x2e, 0x29, 0x4a, 0xcc, 0x2b, 0x4e,
	0x4c, 0x06, 0xa9, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x16, 0x12, 0x12, 0xe3, 0x62,
	0x2b, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x91, 0x60, 0x02, 0x4b, 0x42, 0x79, 0x42, 0x52, 0x5c, 0x1c,
	0xc9, 0xa5, 0x45, 0x45, 0xa9, 0x79, 0xc9, 0x95, 0x12, 0xcc, 0x60, 0x19, 0x38, 0x5f, 0x49, 0x93,
	0x8b, 0x1f, 0x6e, 0x4f, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x92, 0x31, 0x8c, 0xc8, 0xc6, 0x18,
	0x85, 0x73, 0xb1, 0x43, 0x95, 0x0a, 0xf9, 0x70, 0xb1, 0x43, 0x7d, 0x24, 0x24, 0xac, 0x97, 0x58,
	0x90, 0xa9, 0x87, 0xea, 0x56, 0x29, 0x11, 0x54, 0x41, 0x88, 0xc1, 0x4a, 0x62, 0x4d, 0x97, 0x9f,
	0x4c, 0x66, 0x12, 0x50, 0xe2, 0xd6, 0x2f, 0x33, 0xd4, 0x87, 0xea, 0xb7, 0x62, 0xd4, 0x4a, 0x62,
	0x03, 0x7b, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x86, 0xe5, 0x18, 0x96, 0x26, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExtractClient is the client API for Extract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExtractClient interface {
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type extractClient struct {
	cc *grpc.ClientConn
}

func NewExtractClient(cc *grpc.ClientConn) ExtractClient {
	return &extractClient{cc}
}

func (c *extractClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, "/api.Extract/extract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractServer is the server API for Extract service.
type ExtractServer interface {
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
}

// UnimplementedExtractServer can be embedded to have forward compatible implementations.
type UnimplementedExtractServer struct {
}

func (*UnimplementedExtractServer) Extract(ctx context.Context, req *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extract not implemented")
}

func RegisterExtractServer(s *grpc.Server, srv ExtractServer) {
	s.RegisterService(&_Extract_serviceDesc, srv)
}

func _Extract_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Extract/Extract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Extract_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Extract",
	HandlerType: (*ExtractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "extract",
			Handler:    _Extract_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extract.proto",
}
