// Code generated by protoc-gen-go. DO NOT EDIT.
// source: initiate.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitiateRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiateRequest) Reset()         { *m = InitiateRequest{} }
func (m *InitiateRequest) String() string { return proto.CompactTextString(m) }
func (*InitiateRequest) ProtoMessage()    {}
func (*InitiateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c282291b2fabaa, []int{0}
}

func (m *InitiateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiateRequest.Unmarshal(m, b)
}
func (m *InitiateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiateRequest.Marshal(b, m, deterministic)
}
func (m *InitiateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiateRequest.Merge(m, src)
}
func (m *InitiateRequest) XXX_Size() int {
	return xxx_messageInfo_InitiateRequest.Size(m)
}
func (m *InitiateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitiateRequest proto.InternalMessageInfo

func (m *InitiateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InitiateRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InitiateRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type InitiateResponse struct {
	Secret                   string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	SecretHash               string   `protobuf:"bytes,2,opt,name=secretHash,proto3" json:"secretHash,omitempty"`
	ContractFee              string   `protobuf:"bytes,3,opt,name=contractFee,proto3" json:"contractFee,omitempty"`
	RefundFee                string   `protobuf:"bytes,4,opt,name=refundFee,proto3" json:"refundFee,omitempty"`
	ContractAddress          string   `protobuf:"bytes,5,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	ContractBytes            string   `protobuf:"bytes,6,opt,name=contractBytes,proto3" json:"contractBytes,omitempty"`
	ContractTransaction      string   `protobuf:"bytes,7,opt,name=contractTransaction,proto3" json:"contractTransaction,omitempty"`
	ContractTransactionBytes string   `protobuf:"bytes,8,opt,name=contractTransactionBytes,proto3" json:"contractTransactionBytes,omitempty"`
	ContractRefund           string   `protobuf:"bytes,9,opt,name=contractRefund,proto3" json:"contractRefund,omitempty"`
	ContractRefundBytes      string   `protobuf:"bytes,10,opt,name=contractRefundBytes,proto3" json:"contractRefundBytes,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *InitiateResponse) Reset()         { *m = InitiateResponse{} }
func (m *InitiateResponse) String() string { return proto.CompactTextString(m) }
func (*InitiateResponse) ProtoMessage()    {}
func (*InitiateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6c282291b2fabaa, []int{1}
}

func (m *InitiateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiateResponse.Unmarshal(m, b)
}
func (m *InitiateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiateResponse.Marshal(b, m, deterministic)
}
func (m *InitiateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiateResponse.Merge(m, src)
}
func (m *InitiateResponse) XXX_Size() int {
	return xxx_messageInfo_InitiateResponse.Size(m)
}
func (m *InitiateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitiateResponse proto.InternalMessageInfo

func (m *InitiateResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *InitiateResponse) GetSecretHash() string {
	if m != nil {
		return m.SecretHash
	}
	return ""
}

func (m *InitiateResponse) GetContractFee() string {
	if m != nil {
		return m.ContractFee
	}
	return ""
}

func (m *InitiateResponse) GetRefundFee() string {
	if m != nil {
		return m.RefundFee
	}
	return ""
}

func (m *InitiateResponse) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *InitiateResponse) GetContractBytes() string {
	if m != nil {
		return m.ContractBytes
	}
	return ""
}

func (m *InitiateResponse) GetContractTransaction() string {
	if m != nil {
		return m.ContractTransaction
	}
	return ""
}

func (m *InitiateResponse) GetContractTransactionBytes() string {
	if m != nil {
		return m.ContractTransactionBytes
	}
	return ""
}

func (m *InitiateResponse) GetContractRefund() string {
	if m != nil {
		return m.ContractRefund
	}
	return ""
}

func (m *InitiateResponse) GetContractRefundBytes() string {
	if m != nil {
		return m.ContractRefundBytes
	}
	return ""
}

func init() {
	proto.RegisterType((*InitiateRequest)(nil), "api.InitiateRequest")
	proto.RegisterType((*InitiateResponse)(nil), "api.InitiateResponse")
}

func init() { proto.RegisterFile("initiate.proto", fileDescriptor_d6c282291b2fabaa) }

var fileDescriptor_d6c282291b2fabaa = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x16, 0xda, 0x64, 0x80, 0x16, 0x86, 0x3f, 0xab, 0xaa, 0x50, 0x15, 0x21, 0x54,
	0xb1, 0x68, 0xf8, 0xd9, 0x75, 0x07, 0x0b, 0x04, 0x3b, 0x14, 0xb1, 0x44, 0x42, 0x26, 0x35, 0xc5,
	0x12, 0xd8, 0xc1, 0x76, 0x90, 0xba, 0xe5, 0x0a, 0xdc, 0x80, 0x2b, 0x71, 0x05, 0x0e, 0x82, 0xe2,
	0xc4, 0x34, 0x8d, 0xca, 0x2e, 0xf3, 0xbd, 0x37, 0xf3, 0xec, 0x78, 0xa0, 0xc3, 0x05, 0x37, 0x9c,
	0x1a, 0x36, 0x4a, 0x95, 0x34, 0x12, 0x9b, 0x34, 0xe5, 0xbd, 0xfe, 0x54, 0xca, 0xe9, 0x0b, 0x8b,
	0x68, 0xca, 0x23, 0x2a, 0x84, 0x34, 0xd4, 0x70, 0x29, 0x74, 0x61, 0x09, 0x1f, 0xa0, 0x7b, 0x53,
	0x36, 0xc5, 0xec, 0x2d, 0x63, 0xda, 0x20, 0x81, 0x36, 0x9d, 0x4c, 0x14, 0xd3, 0x9a, 0x78, 0x03,
	0x6f, 0x18, 0xc4, 0xae, 0xc4, 0x3d, 0x68, 0xd1, 0x57, 0x99, 0x09, 0x43, 0x1a, 0x03, 0x6f, 0xe8,
	0xc5, 0x65, 0x85, 0x3d, 0xf0, 0x93, 0x4c, 0x29, 0x26, 0x92, 0x19, 0x69, 0xda, 0x96, 0xbf, 0x3a,
	0xfc, 0x6a, 0xc2, 0xe6, 0x3c, 0x41, 0xa7, 0x52, 0x68, 0x96, 0x0f, 0xd2, 0x2c, 0x51, 0xcc, 0x94,
	0x09, 0x65, 0x85, 0x07, 0x00, 0xc5, 0xd7, 0x35, 0xd5, 0xcf, 0x36, 0x24, 0x88, 0x2b, 0x04, 0x07,
	0xb0, 0x96, 0x48, 0x61, 0x14, 0x4d, 0xcc, 0x15, 0x63, 0x65, 0x56, 0x15, 0x61, 0x1f, 0x02, 0xc5,
	0x9e, 0x32, 0x31, 0xc9, 0xf5, 0x15, 0xab, 0xcf, 0x01, 0x0e, 0xa1, 0xeb, 0xcc, 0x17, 0xe5, 0x15,
	0x57, 0xad, 0xa7, 0x8e, 0xf1, 0x10, 0x36, 0x1c, 0xba, 0x9c, 0x19, 0xa6, 0x49, 0xcb, 0xfa, 0x16,
	0x21, 0x9e, 0xc0, 0xb6, 0x03, 0x77, 0x8a, 0x0a, 0x4d, 0x93, 0xfc, 0xdf, 0x92, 0xb6, 0xf5, 0x2e,
	0x93, 0x70, 0x0c, 0x64, 0x09, 0x2e, 0x22, 0x7c, 0xdb, 0xf6, 0xaf, 0x8e, 0x47, 0xd0, 0x71, 0x5a,
	0x6c, 0xaf, 0x44, 0x02, 0xdb, 0x51, 0xa3, 0xd5, 0x53, 0x15, 0xa4, 0x18, 0x0f, 0x8b, 0xa7, 0xaa,
	0x48, 0x67, 0xf7, 0xe0, 0xbb, 0x37, 0xc2, 0x5b, 0xf0, 0xdd, 0x1a, 0xe1, 0xce, 0x88, 0xa6, 0x7c,
	0x54, 0x5b, 0x90, 0xde, 0x6e, 0x8d, 0x16, 0x8f, 0x1a, 0xee, 0x7f, 0x7c, 0xff, 0x7c, 0x36, 0xb6,
	0xc2, 0xf5, 0xe8, 0xfd, 0x34, 0x72, 0x23, 0xc6, 0xde, 0xf1, 0x63, 0xcb, 0xae, 0xda, 0xf9, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x89, 0xf2, 0xed, 0x9f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InitiateClient is the client API for Initiate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InitiateClient interface {
	Initiate(ctx context.Context, in *InitiateRequest, opts ...grpc.CallOption) (*InitiateResponse, error)
}

type initiateClient struct {
	cc *grpc.ClientConn
}

func NewInitiateClient(cc *grpc.ClientConn) InitiateClient {
	return &initiateClient{cc}
}

func (c *initiateClient) Initiate(ctx context.Context, in *InitiateRequest, opts ...grpc.CallOption) (*InitiateResponse, error) {
	out := new(InitiateResponse)
	err := c.cc.Invoke(ctx, "/api.Initiate/initiate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitiateServer is the server API for Initiate service.
type InitiateServer interface {
	Initiate(context.Context, *InitiateRequest) (*InitiateResponse, error)
}

// UnimplementedInitiateServer can be embedded to have forward compatible implementations.
type UnimplementedInitiateServer struct {
}

func (*UnimplementedInitiateServer) Initiate(ctx context.Context, req *InitiateRequest) (*InitiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initiate not implemented")
}

func RegisterInitiateServer(s *grpc.Server, srv InitiateServer) {
	s.RegisterService(&_Initiate_serviceDesc, srv)
}

func _Initiate_Initiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitiateServer).Initiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Initiate/Initiate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitiateServer).Initiate(ctx, req.(*InitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Initiate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Initiate",
	HandlerType: (*InitiateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initiate",
			Handler:    _Initiate_Initiate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "initiate.proto",
}
