// Code generated by protoc-gen-go. DO NOT EDIT.
// source: participate.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParticipateRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipateRequest) Reset()         { *m = ParticipateRequest{} }
func (m *ParticipateRequest) String() string { return proto.CompactTextString(m) }
func (*ParticipateRequest) ProtoMessage()    {}
func (*ParticipateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_650061c0598a705c, []int{0}
}

func (m *ParticipateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipateRequest.Unmarshal(m, b)
}
func (m *ParticipateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipateRequest.Marshal(b, m, deterministic)
}
func (m *ParticipateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipateRequest.Merge(m, src)
}
func (m *ParticipateRequest) XXX_Size() int {
	return xxx_messageInfo_ParticipateRequest.Size(m)
}
func (m *ParticipateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipateRequest proto.InternalMessageInfo

func (m *ParticipateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ParticipateRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ParticipateRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ParticipateRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type ParticipateResponse struct {
	ContractFee          string   `protobuf:"bytes,1,opt,name=contractFee,proto3" json:"contractFee,omitempty"`
	RefundFee            string   `protobuf:"bytes,2,opt,name=refundFee,proto3" json:"refundFee,omitempty"`
	Contract             string   `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	ContractTransaction  string   `protobuf:"bytes,4,opt,name=contractTransaction,proto3" json:"contractTransaction,omitempty"`
	RefundTransaction    string   `protobuf:"bytes,5,opt,name=refundTransaction,proto3" json:"refundTransaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipateResponse) Reset()         { *m = ParticipateResponse{} }
func (m *ParticipateResponse) String() string { return proto.CompactTextString(m) }
func (*ParticipateResponse) ProtoMessage()    {}
func (*ParticipateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_650061c0598a705c, []int{1}
}

func (m *ParticipateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipateResponse.Unmarshal(m, b)
}
func (m *ParticipateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipateResponse.Marshal(b, m, deterministic)
}
func (m *ParticipateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipateResponse.Merge(m, src)
}
func (m *ParticipateResponse) XXX_Size() int {
	return xxx_messageInfo_ParticipateResponse.Size(m)
}
func (m *ParticipateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipateResponse proto.InternalMessageInfo

func (m *ParticipateResponse) GetContractFee() string {
	if m != nil {
		return m.ContractFee
	}
	return ""
}

func (m *ParticipateResponse) GetRefundFee() string {
	if m != nil {
		return m.RefundFee
	}
	return ""
}

func (m *ParticipateResponse) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ParticipateResponse) GetContractTransaction() string {
	if m != nil {
		return m.ContractTransaction
	}
	return ""
}

func (m *ParticipateResponse) GetRefundTransaction() string {
	if m != nil {
		return m.RefundTransaction
	}
	return ""
}

func init() {
	proto.RegisterType((*ParticipateRequest)(nil), "api.ParticipateRequest")
	proto.RegisterType((*ParticipateResponse)(nil), "api.ParticipateResponse")
}

func init() { proto.RegisterFile("participate.proto", fileDescriptor_650061c0598a705c) }

var fileDescriptor_650061c0598a705c = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0x95, 0xdb, 0x7e, 0xfd, 0xe8, 0x74, 0x81, 0x3a, 0x45, 0x60, 0x45, 0x5d, 0x54, 0x59, 0x55,
	0x08, 0x25, 0xfc, 0xec, 0x38, 0x00, 0x6b, 0x14, 0xb1, 0x64, 0x33, 0x38, 0xa6, 0xb5, 0x00, 0xdb,
	0xd8, 0x4e, 0x25, 0xb6, 0x5c, 0x81, 0x93, 0x21, 0xae, 0xc0, 0x41, 0x50, 0x9d, 0xb4, 0x0d, 0x0a,
	0xbb, 0x79, 0xf3, 0x9e, 0xe7, 0x8d, 0xdf, 0xc0, 0xc4, 0x92, 0x0b, 0x4a, 0x28, 0x4b, 0x41, 0x66,
	0xd6, 0x99, 0x60, 0xb0, 0x4f, 0x56, 0x25, 0xb3, 0xa5, 0x31, 0xcb, 0x67, 0x99, 0x93, 0x55, 0x39,
	0x69, 0x6d, 0x02, 0x05, 0x65, 0xb4, 0xaf, 0x25, 0xe9, 0x1a, 0xf0, 0x76, 0xff, 0xae, 0x90, 0xaf,
	0x95, 0xf4, 0x01, 0x39, 0xfc, 0xa7, 0xb2, 0x74, 0xd2, 0x7b, 0xce, 0xe6, 0x6c, 0x31, 0x2a, 0xb6,
	0x10, 0x8f, 0x61, 0x48, 0x2f, 0xa6, 0xd2, 0x81, 0xf7, 0xe6, 0x6c, 0xc1, 0x8a, 0x06, 0x21, 0xc2,
	0x60, 0x45, 0x7e, 0xc5, 0xfb, 0x51, 0x1e, 0x6b, 0x4c, 0xe0, 0x40, 0x54, 0xce, 0x49, 0x2d, 0xde,
	0xf8, 0x20, 0xf6, 0x77, 0x38, 0xfd, 0x64, 0x30, 0xfd, 0x65, 0xec, 0xad, 0xd1, 0x5e, 0xe2, 0x1c,
	0xc6, 0xc2, 0xe8, 0xe0, 0x48, 0x84, 0x1b, 0x29, 0x1b, 0xf7, 0x76, 0x0b, 0x67, 0x30, 0x72, 0xf2,
	0xb1, 0xd2, 0xe5, 0x86, 0xef, 0x45, 0x7e, 0xdf, 0x88, 0x9e, 0x8d, 0xb8, 0xd9, 0x65, 0x87, 0xf1,
	0x1c, 0xa6, 0xdb, 0xfa, 0xce, 0x91, 0xf6, 0x24, 0x36, 0x49, 0x34, 0xab, 0xfd, 0x45, 0xe1, 0x19,
	0x4c, 0xea, 0xd1, 0x6d, 0xfd, 0xbf, 0xa8, 0xef, 0x12, 0x97, 0x4f, 0x30, 0x6e, 0x7d, 0x09, 0xef,
	0x61, 0xdc, 0x3a, 0x09, 0x9e, 0x64, 0x64, 0x55, 0xd6, 0x0d, 0x3b, 0xe1, 0x5d, 0xa2, 0x0e, 0x23,
	0x4d, 0xde, 0xbf, 0xbe, 0x3f, 0x7a, 0x47, 0xe9, 0x61, 0xbe, 0xbe, 0xc8, 0x5b, 0xb3, 0xae, 0xd9,
	0xe9, 0xc3, 0x30, 0xde, 0xef, 0xea, 0x27, 0x00, 0x00, 0xff, 0xff, 0x48, 0x72, 0x01, 0xe4, 0xf7,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ParticipateClient is the client API for Participate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParticipateClient interface {
	Participate(ctx context.Context, in *ParticipateRequest, opts ...grpc.CallOption) (*ParticipateResponse, error)
}

type participateClient struct {
	cc *grpc.ClientConn
}

func NewParticipateClient(cc *grpc.ClientConn) ParticipateClient {
	return &participateClient{cc}
}

func (c *participateClient) Participate(ctx context.Context, in *ParticipateRequest, opts ...grpc.CallOption) (*ParticipateResponse, error) {
	out := new(ParticipateResponse)
	err := c.cc.Invoke(ctx, "/api.Participate/participate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParticipateServer is the server API for Participate service.
type ParticipateServer interface {
	Participate(context.Context, *ParticipateRequest) (*ParticipateResponse, error)
}

// UnimplementedParticipateServer can be embedded to have forward compatible implementations.
type UnimplementedParticipateServer struct {
}

func (*UnimplementedParticipateServer) Participate(ctx context.Context, req *ParticipateRequest) (*ParticipateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Participate not implemented")
}

func RegisterParticipateServer(s *grpc.Server, srv ParticipateServer) {
	s.RegisterService(&_Participate_serviceDesc, srv)
}

func _Participate_Participate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParticipateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipateServer).Participate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Participate/Participate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipateServer).Participate(ctx, req.(*ParticipateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Participate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Participate",
	HandlerType: (*ParticipateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "participate",
			Handler:    _Participate_Participate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "participate.proto",
}
