// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redeem.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RedeemRequest struct {
	ContractBytes        string   `protobuf:"bytes,1,opt,name=contractBytes,proto3" json:"contractBytes,omitempty"`
	TransactionBytes     string   `protobuf:"bytes,2,opt,name=transactionBytes,proto3" json:"transactionBytes,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedeemRequest) Reset()         { *m = RedeemRequest{} }
func (m *RedeemRequest) String() string { return proto.CompactTextString(m) }
func (*RedeemRequest) ProtoMessage()    {}
func (*RedeemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2705a03ec4937aae, []int{0}
}

func (m *RedeemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemRequest.Unmarshal(m, b)
}
func (m *RedeemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemRequest.Marshal(b, m, deterministic)
}
func (m *RedeemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemRequest.Merge(m, src)
}
func (m *RedeemRequest) XXX_Size() int {
	return xxx_messageInfo_RedeemRequest.Size(m)
}
func (m *RedeemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemRequest proto.InternalMessageInfo

func (m *RedeemRequest) GetContractBytes() string {
	if m != nil {
		return m.ContractBytes
	}
	return ""
}

func (m *RedeemRequest) GetTransactionBytes() string {
	if m != nil {
		return m.TransactionBytes
	}
	return ""
}

func (m *RedeemRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *RedeemRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type RedeemResponse struct {
	RedeemFee            string   `protobuf:"bytes,1,opt,name=redeemFee,proto3" json:"redeemFee,omitempty"`
	RedeemTransaction    string   `protobuf:"bytes,2,opt,name=redeemTransaction,proto3" json:"redeemTransaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedeemResponse) Reset()         { *m = RedeemResponse{} }
func (m *RedeemResponse) String() string { return proto.CompactTextString(m) }
func (*RedeemResponse) ProtoMessage()    {}
func (*RedeemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2705a03ec4937aae, []int{1}
}

func (m *RedeemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedeemResponse.Unmarshal(m, b)
}
func (m *RedeemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedeemResponse.Marshal(b, m, deterministic)
}
func (m *RedeemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemResponse.Merge(m, src)
}
func (m *RedeemResponse) XXX_Size() int {
	return xxx_messageInfo_RedeemResponse.Size(m)
}
func (m *RedeemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemResponse proto.InternalMessageInfo

func (m *RedeemResponse) GetRedeemFee() string {
	if m != nil {
		return m.RedeemFee
	}
	return ""
}

func (m *RedeemResponse) GetRedeemTransaction() string {
	if m != nil {
		return m.RedeemTransaction
	}
	return ""
}

func init() {
	proto.RegisterType((*RedeemRequest)(nil), "api.RedeemRequest")
	proto.RegisterType((*RedeemResponse)(nil), "api.RedeemResponse")
}

func init() { proto.RegisterFile("redeem.proto", fileDescriptor_2705a03ec4937aae) }

var fileDescriptor_2705a03ec4937aae = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x49, 0x2b, 0xc1, 0x0e, 0xd6, 0x8f, 0x11, 0x25, 0x84, 0x1e, 0x24, 0x78, 0x90, 0x22,
	0x09, 0xea, 0xcd, 0xa3, 0x07, 0xf1, 0x1c, 0x3c, 0x7a, 0x59, 0xd7, 0xa1, 0x04, 0x74, 0x67, 0xdd,
	0x9d, 0x0a, 0xbd, 0xfa, 0x0a, 0xe2, 0x93, 0xf9, 0x0a, 0x3e, 0x88, 0xb8, 0x13, 0x2d, 0xa1, 0xc7,
	0xff, 0xc7, 0xcc, 0xfe, 0x76, 0x60, 0x27, 0xd0, 0x13, 0xd1, 0x4b, 0xed, 0x03, 0x0b, 0xe3, 0xd8,
	0xf8, 0xae, 0x9c, 0x2d, 0x98, 0x17, 0xcf, 0xd4, 0x18, 0xdf, 0x35, 0xc6, 0x39, 0x16, 0x23, 0x1d,
	0xbb, 0xa8, 0x95, 0xea, 0x33, 0x83, 0x69, 0x9b, 0x66, 0x5a, 0x7a, 0x5d, 0x52, 0x14, 0x3c, 0x85,
	0xa9, 0x65, 0x27, 0xc1, 0x58, 0xb9, 0x59, 0x09, 0xc5, 0x22, 0x3b, 0xc9, 0xce, 0x26, 0xed, 0xd0,
	0xc4, 0x39, 0xec, 0x4b, 0x30, 0x2e, 0x1a, 0xfb, 0xbb, 0x4d, 0x8b, 0xa3, 0x54, 0xdc, 0xf0, 0xf1,
	0x18, 0xf2, 0x48, 0x36, 0x90, 0x14, 0xe3, 0xd4, 0xe8, 0x15, 0x96, 0xb0, 0x6d, 0x97, 0x21, 0x90,
	0xb3, 0xab, 0x62, 0x2b, 0x25, 0xff, 0xba, 0x7a, 0x80, 0xdd, 0x3f, 0xac, 0xe8, 0xd9, 0x45, 0xc2,
	0x19, 0x4c, 0xf4, 0x73, 0xb7, 0x44, 0x3d, 0xd3, 0xda, 0xc0, 0x73, 0x38, 0x50, 0x71, 0xbf, 0x7e,
	0xbd, 0x07, 0xda, 0x0c, 0x2e, 0x5b, 0xc8, 0x75, 0x3b, 0xde, 0x41, 0xae, 0x31, 0x62, 0x6d, 0x7c,
	0x57, 0x0f, 0x6e, 0x51, 0x1e, 0x0e, 0x3c, 0x05, 0xa9, 0x8e, 0xde, 0xbf, 0xbe, 0x3f, 0x46, 0x7b,
	0x15, 0x34, 0x6f, 0x17, 0x8d, 0x0e, 0x5f, 0x67, 0xf3, 0xc7, 0x3c, 0x1d, 0xf4, 0xea, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x6e, 0x3a, 0x01, 0x26, 0x83, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RedeemClient is the client API for Redeem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RedeemClient interface {
	Redeem(ctx context.Context, in *RedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error)
}

type redeemClient struct {
	cc *grpc.ClientConn
}

func NewRedeemClient(cc *grpc.ClientConn) RedeemClient {
	return &redeemClient{cc}
}

func (c *redeemClient) Redeem(ctx context.Context, in *RedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error) {
	out := new(RedeemResponse)
	err := c.cc.Invoke(ctx, "/api.Redeem/redeem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedeemServer is the server API for Redeem service.
type RedeemServer interface {
	Redeem(context.Context, *RedeemRequest) (*RedeemResponse, error)
}

// UnimplementedRedeemServer can be embedded to have forward compatible implementations.
type UnimplementedRedeemServer struct {
}

func (*UnimplementedRedeemServer) Redeem(ctx context.Context, req *RedeemRequest) (*RedeemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Redeem not implemented")
}

func RegisterRedeemServer(s *grpc.Server, srv RedeemServer) {
	s.RegisterService(&_Redeem_serviceDesc, srv)
}

func _Redeem_Redeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedeemServer).Redeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Redeem/Redeem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedeemServer).Redeem(ctx, req.(*RedeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Redeem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Redeem",
	HandlerType: (*RedeemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "redeem",
			Handler:    _Redeem_Redeem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redeem.proto",
}
