// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swap.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SwapRequest struct {
	BaseAmount           string   `protobuf:"bytes,1,opt,name=baseAmount,proto3" json:"baseAmount,omitempty"`
	BaseAddress          string   `protobuf:"bytes,2,opt,name=baseAddress,proto3" json:"baseAddress,omitempty"`
	SwapAmount           string   `protobuf:"bytes,3,opt,name=swapAmount,proto3" json:"swapAmount,omitempty"`
	SwapAddress          string   `protobuf:"bytes,4,opt,name=swapAddress,proto3" json:"swapAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwapRequest) Reset()         { *m = SwapRequest{} }
func (m *SwapRequest) String() string { return proto.CompactTextString(m) }
func (*SwapRequest) ProtoMessage()    {}
func (*SwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35a3890a6e60fb7, []int{0}
}

func (m *SwapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapRequest.Unmarshal(m, b)
}
func (m *SwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapRequest.Marshal(b, m, deterministic)
}
func (m *SwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapRequest.Merge(m, src)
}
func (m *SwapRequest) XXX_Size() int {
	return xxx_messageInfo_SwapRequest.Size(m)
}
func (m *SwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwapRequest proto.InternalMessageInfo

func (m *SwapRequest) GetBaseAmount() string {
	if m != nil {
		return m.BaseAmount
	}
	return ""
}

func (m *SwapRequest) GetBaseAddress() string {
	if m != nil {
		return m.BaseAddress
	}
	return ""
}

func (m *SwapRequest) GetSwapAmount() string {
	if m != nil {
		return m.SwapAmount
	}
	return ""
}

func (m *SwapRequest) GetSwapAddress() string {
	if m != nil {
		return m.SwapAddress
	}
	return ""
}

type SwapResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SwapId               string   `protobuf:"bytes,2,opt,name=swapId,proto3" json:"swapId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwapResponse) Reset()         { *m = SwapResponse{} }
func (m *SwapResponse) String() string { return proto.CompactTextString(m) }
func (*SwapResponse) ProtoMessage()    {}
func (*SwapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c35a3890a6e60fb7, []int{1}
}

func (m *SwapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapResponse.Unmarshal(m, b)
}
func (m *SwapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapResponse.Marshal(b, m, deterministic)
}
func (m *SwapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapResponse.Merge(m, src)
}
func (m *SwapResponse) XXX_Size() int {
	return xxx_messageInfo_SwapResponse.Size(m)
}
func (m *SwapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwapResponse proto.InternalMessageInfo

func (m *SwapResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SwapResponse) GetSwapId() string {
	if m != nil {
		return m.SwapId
	}
	return ""
}

func init() {
	proto.RegisterType((*SwapRequest)(nil), "api.SwapRequest")
	proto.RegisterType((*SwapResponse)(nil), "api.SwapResponse")
}

func init() { proto.RegisterFile("swap.proto", fileDescriptor_c35a3890a6e60fb7) }

var fileDescriptor_c35a3890a6e60fb7 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0xd9, 0x76, 0x29, 0x3a, 0x55, 0xd0, 0x08, 0x52, 0x8a, 0x48, 0xc9, 0x49, 0x3c, 0x6c,
	0x50, 0x6f, 0x1e, 0x44, 0x6f, 0x7a, 0xad, 0x4f, 0x30, 0x65, 0x43, 0x09, 0x68, 0x66, 0xec, 0x64,
	0xdd, 0xbb, 0x6f, 0x20, 0x3e, 0x9a, 0xaf, 0xe0, 0x83, 0x48, 0xfe, 0x40, 0x73, 0xfc, 0x7e, 0xcc,
	0xfc, 0xf2, 0x65, 0x00, 0x64, 0x44, 0xee, 0x78, 0x47, 0x81, 0xd4, 0x14, 0xd9, 0x2d, 0x2f, 0xb6,
	0x44, 0xdb, 0x37, 0x6b, 0x90, 0x9d, 0x41, 0xef, 0x29, 0x60, 0x70, 0xe4, 0x25, 0x8f, 0xe8, 0xef,
	0x06, 0xe6, 0xaf, 0x23, 0xf2, 0xda, 0x7e, 0x0c, 0x56, 0x82, 0xba, 0x04, 0xd8, 0xa0, 0xd8, 0xa7,
	0x77, 0x1a, 0x7c, 0x58, 0x34, 0xab, 0xe6, 0xea, 0x70, 0x5d, 0x11, 0xb5, 0x82, 0x79, 0x4a, 0x7d,
	0xbf, 0xb3, 0x22, 0x8b, 0x49, 0x1a, 0xa8, 0x51, 0x34, 0xc4, 0x0a, 0xc5, 0x30, 0xcd, 0x86, 0x3d,
	0x89, 0x86, 0x94, 0x8a, 0xa1, 0xcd, 0x86, 0x0a, 0xe9, 0x07, 0x38, 0xca, 0x95, 0x84, 0xc9, 0x8b,
	0x55, 0xe7, 0x30, 0x93, 0x80, 0x61, 0x90, 0xd2, 0xa7, 0xa4, 0xc4, 0x47, 0xe4, 0x97, 0xbe, 0xd4,
	0x28, 0xe9, 0xf6, 0x19, 0xda, 0xb8, 0xaf, 0x1e, 0xa1, 0x8d, 0x44, 0x9d, 0x74, 0xc8, 0xae, 0xab,
	0x7e, 0xb9, 0x3c, 0xad, 0x48, 0x7e, 0x44, 0x9f, 0x7d, 0xfd, 0xfe, 0xfd, 0x4c, 0x8e, 0xf5, 0x81,
	0xf9, 0xbc, 0x31, 0x71, 0xed, 0xbe, 0xb9, 0xde, 0xcc, 0xd2, 0x91, 0xee, 0xfe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0x14, 0xe4, 0xd1, 0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SwapClient is the client API for Swap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SwapClient interface {
	Swap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResponse, error)
}

type swapClient struct {
	cc *grpc.ClientConn
}

func NewSwapClient(cc *grpc.ClientConn) SwapClient {
	return &swapClient{cc}
}

func (c *swapClient) Swap(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*SwapResponse, error) {
	out := new(SwapResponse)
	err := c.cc.Invoke(ctx, "/api.Swap/swap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwapServer is the server API for Swap service.
type SwapServer interface {
	Swap(context.Context, *SwapRequest) (*SwapResponse, error)
}

// UnimplementedSwapServer can be embedded to have forward compatible implementations.
type UnimplementedSwapServer struct {
}

func (*UnimplementedSwapServer) Swap(ctx context.Context, req *SwapRequest) (*SwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Swap not implemented")
}

func RegisterSwapServer(s *grpc.Server, srv SwapServer) {
	s.RegisterService(&_Swap_serviceDesc, srv)
}

func _Swap_Swap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServer).Swap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Swap/Swap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServer).Swap(ctx, req.(*SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Swap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Swap",
	HandlerType: (*SwapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "swap",
			Handler:    _Swap_Swap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swap.proto",
}
