// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swap.status.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SwapStatusRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwapStatusRequest) Reset()         { *m = SwapStatusRequest{} }
func (m *SwapStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SwapStatusRequest) ProtoMessage()    {}
func (*SwapStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df13c9029afc2b5, []int{0}
}

func (m *SwapStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapStatusRequest.Unmarshal(m, b)
}
func (m *SwapStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapStatusRequest.Marshal(b, m, deterministic)
}
func (m *SwapStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapStatusRequest.Merge(m, src)
}
func (m *SwapStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SwapStatusRequest.Size(m)
}
func (m *SwapStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SwapStatusRequest proto.InternalMessageInfo

func (m *SwapStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SwapStatusResponse struct {
	Status                string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BaseStatus            string   `protobuf:"bytes,2,opt,name=baseStatus,proto3" json:"baseStatus,omitempty"`
	SwapStatus            string   `protobuf:"bytes,3,opt,name=swapStatus,proto3" json:"swapStatus,omitempty"`
	BaseAddress           string   `protobuf:"bytes,4,opt,name=baseAddress,proto3" json:"baseAddress,omitempty"`
	SwapAddress           string   `protobuf:"bytes,5,opt,name=swapAddress,proto3" json:"swapAddress,omitempty"`
	BaseContract          string   `protobuf:"bytes,6,opt,name=baseContract,proto3" json:"baseContract,omitempty"`
	SwapContract          string   `protobuf:"bytes,7,opt,name=swapContract,proto3" json:"swapContract,omitempty"`
	BaseTransaction       string   `protobuf:"bytes,8,opt,name=baseTransaction,proto3" json:"baseTransaction,omitempty"`
	SwapTransaction       string   `protobuf:"bytes,9,opt,name=swapTransaction,proto3" json:"swapTransaction,omitempty"`
	BaseRedeemTransaction string   `protobuf:"bytes,10,opt,name=baseRedeemTransaction,proto3" json:"baseRedeemTransaction,omitempty"`
	SwapRedeemTransaction string   `protobuf:"bytes,11,opt,name=swapRedeemTransaction,proto3" json:"swapRedeemTransaction,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SwapStatusResponse) Reset()         { *m = SwapStatusResponse{} }
func (m *SwapStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SwapStatusResponse) ProtoMessage()    {}
func (*SwapStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7df13c9029afc2b5, []int{1}
}

func (m *SwapStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapStatusResponse.Unmarshal(m, b)
}
func (m *SwapStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapStatusResponse.Marshal(b, m, deterministic)
}
func (m *SwapStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapStatusResponse.Merge(m, src)
}
func (m *SwapStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SwapStatusResponse.Size(m)
}
func (m *SwapStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwapStatusResponse proto.InternalMessageInfo

func (m *SwapStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SwapStatusResponse) GetBaseStatus() string {
	if m != nil {
		return m.BaseStatus
	}
	return ""
}

func (m *SwapStatusResponse) GetSwapStatus() string {
	if m != nil {
		return m.SwapStatus
	}
	return ""
}

func (m *SwapStatusResponse) GetBaseAddress() string {
	if m != nil {
		return m.BaseAddress
	}
	return ""
}

func (m *SwapStatusResponse) GetSwapAddress() string {
	if m != nil {
		return m.SwapAddress
	}
	return ""
}

func (m *SwapStatusResponse) GetBaseContract() string {
	if m != nil {
		return m.BaseContract
	}
	return ""
}

func (m *SwapStatusResponse) GetSwapContract() string {
	if m != nil {
		return m.SwapContract
	}
	return ""
}

func (m *SwapStatusResponse) GetBaseTransaction() string {
	if m != nil {
		return m.BaseTransaction
	}
	return ""
}

func (m *SwapStatusResponse) GetSwapTransaction() string {
	if m != nil {
		return m.SwapTransaction
	}
	return ""
}

func (m *SwapStatusResponse) GetBaseRedeemTransaction() string {
	if m != nil {
		return m.BaseRedeemTransaction
	}
	return ""
}

func (m *SwapStatusResponse) GetSwapRedeemTransaction() string {
	if m != nil {
		return m.SwapRedeemTransaction
	}
	return ""
}

func init() {
	proto.RegisterType((*SwapStatusRequest)(nil), "api.SwapStatusRequest")
	proto.RegisterType((*SwapStatusResponse)(nil), "api.SwapStatusResponse")
}

func init() { proto.RegisterFile("swap.status.proto", fileDescriptor_7df13c9029afc2b5) }

var fileDescriptor_7df13c9029afc2b5 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0x5f, 0x4e, 0x3a, 0x31,
	0x10, 0x07, 0xf0, 0xb0, 0xfc, 0x7e, 0x28, 0x83, 0x4a, 0x68, 0x02, 0x36, 0xc4, 0x18, 0xb2, 0xbe,
	0xf0, 0xb4, 0x1b, 0xff, 0x5c, 0xc0, 0x78, 0x03, 0xe0, 0x02, 0x03, 0x6d, 0x48, 0x13, 0x6d, 0xeb,
	0xb6, 0xc8, 0x83, 0xf1, 0xc5, 0x2b, 0x78, 0x19, 0xef, 0xe1, 0x15, 0x3c, 0x88, 0x99, 0x76, 0x85,
	0x0a, 0x3c, 0xf2, 0x9d, 0xcf, 0x77, 0x48, 0x3a, 0x0b, 0x3d, 0xb7, 0x46, 0x5b, 0x38, 0x8f, 0x7e,
	0xe5, 0x0a, 0x5b, 0x19, 0x6f, 0x58, 0x13, 0xad, 0x1a, 0x5e, 0x2c, 0x8d, 0x59, 0x3e, 0xca, 0x12,
	0xad, 0x2a, 0x51, 0x6b, 0xe3, 0xd1, 0x2b, 0xa3, 0x6b, 0x92, 0x5f, 0x41, 0x6f, 0xba, 0x46, 0x3b,
	0x0d, 0xb5, 0x89, 0x7c, 0x5e, 0x49, 0xe7, 0xd9, 0x19, 0x64, 0x4a, 0xf0, 0xc6, 0xa8, 0x31, 0x6e,
	0x4f, 0x32, 0x25, 0xf2, 0xcf, 0x26, 0xb0, 0x54, 0x39, 0x6b, 0xb4, 0x93, 0x6c, 0x00, 0xad, 0xf8,
	0x77, 0x35, 0xad, 0x7f, 0xb1, 0x4b, 0x80, 0x39, 0x3a, 0x19, 0x35, 0xcf, 0xc2, 0x2c, 0x49, 0x68,
	0xee, 0x36, 0xdb, 0x78, 0x33, 0xce, 0xb7, 0x09, 0x1b, 0x41, 0x87, 0xf4, 0xbd, 0x10, 0x95, 0x74,
	0x8e, 0xff, 0x0b, 0x20, 0x8d, 0x48, 0x90, 0xff, 0x15, 0xff, 0xa3, 0x48, 0x22, 0x96, 0xc3, 0x09,
	0x15, 0x1e, 0x8c, 0xf6, 0x15, 0x2e, 0x3c, 0x6f, 0x05, 0xf2, 0x27, 0x23, 0x43, 0x95, 0x8d, 0x39,
	0x8a, 0x26, 0xcd, 0xd8, 0x18, 0xba, 0xd4, 0x99, 0x55, 0xa8, 0x1d, 0x2e, 0xe8, 0xe5, 0xf8, 0x71,
	0x60, 0xbb, 0x31, 0x49, 0x6a, 0xa6, 0xb2, 0x1d, 0xe5, 0x4e, 0xcc, 0xee, 0xa0, 0x4f, 0xe5, 0x89,
	0x14, 0x52, 0x3e, 0xa5, 0x1e, 0x82, 0x3f, 0x3c, 0xa4, 0x16, 0x2d, 0xda, 0x6f, 0x75, 0x62, 0xeb,
	0xe0, 0xf0, 0x66, 0x0e, 0xb0, 0xbd, 0x1c, 0x9b, 0xc5, 0x97, 0xaf, 0xef, 0x34, 0x28, 0xd0, 0xaa,
	0x62, 0xef, 0xfc, 0xc3, 0xf3, 0xbd, 0x3c, 0x1e, 0x3c, 0xef, 0xbf, 0x7f, 0x7d, 0x7f, 0x64, 0x5d,
	0x76, 0x5a, 0xbe, 0x5c, 0x97, 0xb4, 0xa8, 0x7c, 0x55, 0xe2, 0x6d, 0xde, 0x0a, 0x9f, 0xd2, 0xed,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x29, 0xbf, 0xdd, 0x82, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SwapStatusClient is the client API for SwapStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SwapStatusClient interface {
	Swapstatus(ctx context.Context, in *SwapStatusRequest, opts ...grpc.CallOption) (*SwapStatusResponse, error)
}

type swapStatusClient struct {
	cc *grpc.ClientConn
}

func NewSwapStatusClient(cc *grpc.ClientConn) SwapStatusClient {
	return &swapStatusClient{cc}
}

func (c *swapStatusClient) Swapstatus(ctx context.Context, in *SwapStatusRequest, opts ...grpc.CallOption) (*SwapStatusResponse, error) {
	out := new(SwapStatusResponse)
	err := c.cc.Invoke(ctx, "/api.SwapStatus/swapstatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwapStatusServer is the server API for SwapStatus service.
type SwapStatusServer interface {
	Swapstatus(context.Context, *SwapStatusRequest) (*SwapStatusResponse, error)
}

// UnimplementedSwapStatusServer can be embedded to have forward compatible implementations.
type UnimplementedSwapStatusServer struct {
}

func (*UnimplementedSwapStatusServer) Swapstatus(ctx context.Context, req *SwapStatusRequest) (*SwapStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Swapstatus not implemented")
}

func RegisterSwapStatusServer(s *grpc.Server, srv SwapStatusServer) {
	s.RegisterService(&_SwapStatus_serviceDesc, srv)
}

func _SwapStatus_Swapstatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapStatusServer).Swapstatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SwapStatus/Swapstatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapStatusServer).Swapstatus(ctx, req.(*SwapStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SwapStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SwapStatus",
	HandlerType: (*SwapStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "swapstatus",
			Handler:    _SwapStatus_Swapstatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swap.status.proto",
}
